Issue #84: Async Chassis Control
OkapiLib/OkapiLib pull request #118
Opened 2018-07-26 00:19 UTC by baylessj

### Description of the Change

Add Asynchronous movement functionality to the `ChassisController`s. Can set a target and then call `waitUntilSettled()` when it is desired to wait for the movement to complete.

### Benefits

Can operate a `ChassisController` at the same time as other subsystems. Generally more freedom with movement timing.

### Possible Drawbacks

No intelligent prioritization of movements - if `moveDistanceAsync` is called from two different threads, then the most recent call will always take priority. There is also no protection in the `waitUntilSettled()` function to prevent the goal from being changed.

This is intentional, however, as it was decided that it would be best to prioritize having the ability to override a `waitUntilSettled()` call with, for instance, an emergency stop from a different thread.

### Verification Process

- Wrote Tests
- Run a chassis controller alongside another subsystem
Test Code:
```
  auto chassis =
    ChassisControllerFactory::create({-11, -20}, {10}, AbstractMotor::gearset::red, {4_in, 11.5_in});
  auto asyncMotor = AsyncControllerFactory::posIntegrated(2);

  chassis.moveDistanceAsync(1_m);
  asyncMotor.setTarget(1000);
  chassis.waitUntilSettled();
```

### Applicable Issues

Closes #84

2018-07-26 00:40 UTC, Octogonapus requested changes
I also want to see tests for calling `moveDistance` and then `turnAngle` before `moveDistance` has settled, and vice versa. This will probably require an implementation of `SettledUtil` that never settles (or if you wanted to go the extra mile, an implementation that lets you toggle whether it's settled).

2018-07-26 00:40 UTC, Octogonapus commented on src/api/chassis/controller/chassisControllerPid.cpp
> +        rate->delayUntil(10_ms);
I think there should be a check in these loops the monitor `mode`. What if, while waiting for a `moveDistance` to settle, the user calls `turnAngle`? I think we will still be waiting for the first call to settle.

2018-07-26 00:40 UTC, Octogonapus commented on test/chassisControllerTests.cpp
> +  EXPECT_TRUE(rightController->disabled);
What are you trying to test here? After you call `moveDistanceAsync`, the controllers should actually be enabled while the robot is moving. If this passes, it's because the call to `moveDistanceAsync` fully completes before code execution moves to the assertions. The same goes for the rest of these tests.

2018-07-26 00:43 UTC, Octogonapus commented
If you want this PR to close #84, you need to say "closes" #84, "fixes" #84, etc. You can't have another word in between the keyword and the issue number.

2018-07-26 14:42 UTC, baylessj commented on test/chassisControllerTests.cpp
> +  EXPECT_TRUE(rightController->disabled);
This is the result of some poor "find and replace" usage to remove usage of `Controller->enabled`, which obviously didn't compile. I'll take a closer look over everything to make sure that it's `EXPECT_FALSE` where necessary

2018-07-29 17:15 UTC, Octogonapus approved these changes

2018-07-30 03:39 UTC, merged

2018-07-30 15:38 UTC, Octogonapus commented
@baylessj Please do not merge a PR that has the `needs docs` label without writing + linking the docs. Additionally, I wanted you to test this with real hardware before merging.

2018-07-30 23:28 UTC, baylessj commented
Ah my bad, I saw the approval and figured it was good to go. I'll take care of the docs tonight.

2018-07-30 23:39 UTC, Octogonapus commented
@baylessj I am currently doing the docs.

2018-07-30 23:40 UTC, Octogonapus commented
Docs: https://github.com/purduesigbots/pros-docs/commit/67853df86d183abfb21bd285024ba32b01ac1ff8

2018-07-30 23:47 UTC, baylessj commented
Well that works too lol. Thanks!